# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-arm64/blas-1.0-openblas.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/bzip2-1.0.8-h620ffc9_4.conda
https://conda.anaconda.org/conda-forge/osx-arm64/c-ares-1.19.1-hb547adb_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/ca-certificates-2023.7.22-hf0a4a13_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/giflib-5.2.1-h80987f9_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jpeg-9e-h80987f9_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libbrotlicommon-1.0.9-h1a8c8d9_8.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/libcxx-14.0.6-h848a8c0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libdeflate-1.17-h80987f9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libev-4.33-h642e427_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/libffi-3.4.4-hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libiconv-1.16-h1a28f6b_2.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libsodium-1.0.18-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libwebp-base-1.2.4-h80987f9_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libzlib-1.2.13-h03a7124_4.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/llvm-openmp-14.0.6-hc6e5704_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ncurses-6.4-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.36-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/xz-5.2.10-h80987f9_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/flatbuffers-22.12.06-hb7217d7_2.conda
https://conda.anaconda.org/conda-forge/osx-arm64/icu-70.1-h6b3803e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/lerc-3.0-hc377ac9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libabseil-20220623.0-cxx17_h28b99d4_6.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libaec-1.0.6-hb7217d7_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libbrotlidec-1.0.9-h1a8c8d9_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/libbrotlienc-1.0.9-h1a8c8d9_8.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/libedit-3.1.20221030-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libgfortran5-11.3.0-h009349e_28.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libprotobuf-3.21.12-hb5ab8b9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libsqlite-3.42.0-hb31c410_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/lz4-c-1.9.4-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nspr-4.33-hc377ac9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/openssl-3.1.2-h53f4e23_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pcre-8.45-hc377ac9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/re2-2023.02.01-hb7217d7_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/readline-8.2-h1a28f6b_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/snappy-1.1.10-h17c5cce_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zeromq-4.3.4-hc377ac9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/zlib-1.2.13-h03a7124_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/brotli-bin-1.0.9-h1a8c8d9_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/krb5-1.20.1-h69eda48_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libgfortran-5.0.0-11_3_0_hca03da5_28.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libgrpc-1.51.1-hb15be72_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libllvm14-14.0.6-h7ec7a93_3.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libnghttp2-1.52.0-hae82a92_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libpng-1.6.39-h80987f9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libssh2-1.11.0-h7a5bd25_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libxml2-2.9.14-h9d8dfc2_4.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/sqlite-3.41.2-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tk-8.6.12-hb8d0fd4_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zstd-1.5.5-hd90d995_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/brotli-1.0.9-h1a8c8d9_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/freetype-2.10.4-h17b34a0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/gettext-0.21.0-h826f4ad_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libclang13-14.0.6-default_h24352ff_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libcurl-8.1.2-h912dcd9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libopenblas-0.3.21-h269037a_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libtiff-4.5.0-h313beb8_2.conda
https://conda.anaconda.org/conda-forge/osx-arm64/libxslt-1.1.35-ha8fb468_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/nss-3.74-h142855e_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/python-3.10.11-h3ba56d0_0_cpython.conda
https://conda.anaconda.org/conda-forge/noarch/absl-py-1.4.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/appnope-0.1.2-py310hca03da5_1001.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/attrs-22.1.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/blinker-1.6.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/cached_property-1.5.2-pyha770c72_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-5.3.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2023.7.22-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/click-8.1.6-unix_pyh707e725_0.conda
https://conda.anaconda.org/conda-forge/noarch/cycler-0.11.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/debugpy-1.5.1-py310hc377ac9_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/entrypoints-0.4-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/gast-0.4.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/glib-2.69.1-h514c7bf_2.conda
https://conda.anaconda.org/conda-forge/osx-arm64/hdf5-1.14.0-nompi_h6b85c65_102.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/idna-3.4-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipython_genutils-0.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/joblib-1.2.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyterlab_widgets-3.0.5-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/keras-2.11.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/kiwisolver-1.4.4-py310h313beb8_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/lcms2-2.15-h481adae_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libclang-14.0.6-default_h1b80db6_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libwebp-1.2.4-ha3663a8_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/markupsafe-2.1.1-py310h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/mistune-0.8.4-py310h1a28f6b_1000.conda
https://conda.anaconda.org/conda-forge/noarch/munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/nest-asyncio-1.5.6-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numpy-base-1.24.3-py310haf87e8b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/packaging-23.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pandocfilters-1.5.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ply-3.11-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/prometheus_client-0.14.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/psutil-5.9.0-py310h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pygments-2.15.1-py310hca03da5_1.conda
https://conda.anaconda.org/conda-forge/noarch/pyjwt-2.8.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyparsing-3.0.9-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/pyrsistent-0.18.0-py310h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pysocks-1.7.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-fastjsonschema-2.16.2-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-flatbuffers-23.5.26-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/python_abi-3.10-2_cp310.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/pytz-2022.7-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyzmq-23.2.0-py310hc377ac9_0.conda
https://repo.anaconda.com/pkgs/main/noarch/send2trash-1.8.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/setuptools-67.8.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/sniffio-1.2.0-py310hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/soupsieve-2.4-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tenacity-8.2.2-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/tensorboard-plugin-wit-1.8.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/termcolor-2.3.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tomli-2.0.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tornado-6.2-py310h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/traitlets-5.7.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/typing_extensions-4.5.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/webencodings-0.5.1-py310hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/wheel-0.38.4-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/widgetsnbextension-4.0.5-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.16.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/anyio-3.5.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/astunparse-1.6.3-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/babel-2.11.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/beautifulsoup4-4.12.2-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/bleach-4.1.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/cached-property-1.5.2-hd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/cffi-1.15.1-py310h80987f9_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/comm-0.1.2-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/frozenlist-1.4.0-py310h2aa6e3c_0.conda
https://conda.anaconda.org/conda-forge/noarch/google-pasta-0.2.0-pyh8c360ce_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/grpcio-1.51.1-py310h63a0e3a_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/gstreamer-1.14.1-h80987f9_1.conda
https://conda.anaconda.org/conda-forge/noarch/importlib-metadata-6.8.0-pyha770c72_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jedi-0.18.1-py310hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jinja2-3.1.2-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jsonschema-4.17.3-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_core-5.3.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/lxml-4.9.1-py310h02f21da_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/matplotlib-inline-0.1.6-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/multidict-6.0.4-py310h8e9501a_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numpy-1.24.3-py310hb93e574_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pillow-9.4.0-py310h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pip-23.0.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/plotly-5.9.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pooch-1.4.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/protobuf-4.21.12-py310h0f1eb42_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyu2f-0.1.5-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/qtpy-2.2.0-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/rsa-4.9-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/sip-6.6.2-py310hc377ac9_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/tensorboard-data-server-0.6.1-py310hfc83b78_4.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/terminado-0.17.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tinycss2-1.2.1-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/typing-extensions-4.5.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/websocket-client-0.58.0-py310hca03da5_4.conda
https://conda.anaconda.org/conda-forge/noarch/werkzeug-2.3.6-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/wrapt-1.15.0-py310h8e9501a_0.conda
https://conda.anaconda.org/conda-forge/noarch/aiosignal-1.3.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/argon2-cffi-bindings-21.2.0-py310h1a28f6b_0.conda
https://conda.anaconda.org/conda-forge/noarch/async-timeout-4.0.2-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/bottleneck-1.3.5-py310h96f19d2_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/brotlipy-0.7.0-py310h1a28f6b_1002.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/contourpy-1.0.5-py310h525c30c_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/cryptography-38.0.4-py310hfc83b78_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/gst-plugins-base-1.14.1-h313beb8_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/h5py-3.9.0-nompi_py310he3619cb_100.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_client-7.4.9-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/markdown-3.4.4-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbformat-5.7.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numexpr-2.8.4-py310hecc3335_1.conda
https://conda.anaconda.org/conda-forge/noarch/opt_einsum-3.3.0-pyhd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/pyqt5-sip-12.11.0-py310hc377ac9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/scipy-1.10.1-py310h20cbe94_1.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/yarl-1.9.2-py310h2aa6e3c_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/aiohttp-3.8.5-py310h2aa6e3c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/argon2-cffi-21.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ipython-8.12.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/keras-preprocessing-1.1.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/matplotlib-base-3.7.1-py310h46d7db6_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbclient-0.5.13-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/oauthlib-3.2.2-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/pandas-1.5.3-py310h46d7db6_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyopenssl-23.0.0-py310hca03da5_0.conda
https://conda.anaconda.org/anaconda/osx-arm64/scikit-learn-1.0.2-py310h59830a0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/ipykernel-6.19.2-py310h33ce5c2_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/matplotlib-3.7.1-py310hb6292c7_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbconvert-6.5.4-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-1.3.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/seaborn-0.12.2-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/urllib3-1.26.15-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/google-auth-2.22.0-pyh1a96a4e_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ipywidgets-8.0.4-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_console-6.6.3-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_server-1.23.4-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/google-auth-oauthlib-0.4.6-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyterlab_server-2.22.0-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/notebook-shim-0.2.2-py310hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbclassic-0.5.5-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/noarch/tensorboard-2.11.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/notebook-6.5.4-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/tensorflow-base-2.11.0-cpu_py310hb1e6bfe_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/jupyter-1.0.0-py310hbe9552e_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyterlab-3.5.3-py310hca03da5_0.conda
https://conda.anaconda.org/conda-forge/osx-arm64/rise-5.7.1-py310hbe9552e_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/tensorflow-estimator-2.11.0-cpu_py310h238a819_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-arm64/tensorflow-2.11.0-cpu_py310h6ecea76_0.tar.bz2
